# Generated by Django 5.2.1 on 2025-06-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnode',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
