# Generated by Django 5.2.1 on 2025-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_userquery_email_userquery_name_userquery_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
