# Generated by Django 5.2.1 on 2025-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_userquery_satisfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnode',
            name='title',
            field=models.CharField(),
        ),
    ]
