# Generated by Django 5.2.1 on 2025-06-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_chatnode_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='userquery',
            name='conversation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
